Nov 10 11:34:56 localhost gdb: detected unhandled Python exception
